apiVersion: v1
kind: Service
metadata:
  name: {{ include "llm-api.fullname" . }}-api
  labels:
    {{- include "llm-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      protocol: TCP
      name: http
      {{- if eq .Values.api.service.type "NodePort" }}
      nodePort: {{ .Values.api.service.nodePort }}
      {{- end }}
  selector:
    {{- include "llm-api.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api