apiVersion: v1
kind: Service
metadata:
  name: {{ include "llm-api.fullname" . }}-ollama
  labels:
    {{- include "llm-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
spec:
  type: {{ .Values.ollama.service.type }}
  ports:
    - port: {{ .Values.ollama.service.port }}
      targetPort: {{ .Values.ollama.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "llm-api.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ollama