apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-api
  labels:
    app: llm-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-api
  template:
    metadata:
      labels:
        app: llm-api
    spec:
      containers:
      - name: api
        image: rrondot/llm-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: OLLAMA_URL
          value: "http://ollama-service:11434"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256mi"
            cpu: "256mi"
          limits:
            memory: "256mi"
            cpu: "256mi"
---
apiVersion: v1
kind: Service
metadata:
  name: llm-api-service
  labels:
    app: llm-api
spec:
  selector:
    app: llm-api
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: LoadBalancer